on:
  push:
    branches:
      - trunk
      - renovate/**
  pull_request:
    branches:
      - trunk

name: Run checks
jobs:
  check:
    uses: msfjarvis/shared-workflows/.github/workflows/test-flakes-project.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
